spring.application.name=consultorio-medico-api
# 1. URL de conexión
spring.datasource.url=jdbc:postgresql://localhost:5433/consultorio-bd

# 2. Credenciales
spring.datasource.username=postgres
spring.datasource.password=postgres

# 3. Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. Configuración de Hibernate/JPA
#Solo verifica que las tablas y columnas en la base de datos coincidan con java
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true